name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          optimize: css, xml
          plugin_introduction: yes
          plugin_introduction_title: "About me"
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
          plugin_languages: yes
          plugin_languages_threshold: 2%
